### ISSUE TITLE
CSS Best Practices & Trends

### ISSUE THREAD

**Issue by wwsun** [wwsun/wwsun.github.com#2]
## Build Tools

- [Browsersync]()

```javascript
// Compile sass into CSS & auto-inject into browsers
gulp.task('sass', function () {
  return gulp.src("app/scss/*.scss")
    .pipe(sass())
    .pipe(gulp.dest('app/css'))
    .pipe(browserSync.tream());
});
```

## Critical CSS

CSS blocks the rendering of your web page

- [Ctirical CSS inline](https://github.com/addyosmani/critical)
- Other CSS 

```javascript
gulp.task('critical', ['build'], function(cb) {
  critical.generate({
    inline: true,
    minify: true,
    width: 320,
    height: 480
  });
});
```

## Lint Tools

- [CSSLint](https://github.com/CSSLint/csslint)
- [SCSS-lint](https://github.com/brigade/scss-lint)
- [SASS Lint](https://github.com/sasstools/sass-lint)
- [stylelint](https://github.com/stylelint/stylelint) - SASS Support, JS Only, Custom Rules, PostCSS

Using stylelint:

```javascript
gulp.task('lint:css', function () {
  return gulp.src('src/**/*.css')
    .pipe(postcss([
      stylelint({/* your options */}),
      reporter({clearMessages: true}),
    ]))
});
```

## SVG

Icon Fonts:

- Rendering issues
- Bad for Accessibility
- Authoring is hard

SVG:

- Easy to animate
- Multi-color icons

References:

- [Icon Fonts performance issues](https://github.com/blog/2112-delivering-octicons-with-svg)
- [SVG Animation Demos](http://codepen.io/suez/pen/dPqxoM)
- [CSS-Tricks - Using SVG](https://css-tricks.com/snippets/css/a-guide-to-flexbox/)

```css
.svg-icon {
  height: 100px;
  overflow: visible;
  width: 100px;
}
.svg-icon  path {
  animation: animatePath 5s 1s forwards infinite;
  fill: none;
  stroke: rgba(255, 255, 255, .9);
  stroke-width: 0.45;
}
```

## CSS Modules

- Scoped locally
- Explicit dependencies
- Makes CSS modular & resuable

### Example

components/button.css

```css
.normal { /* ... */ }
.disabled { /* ... */ }
.error { /* ... */ }
```

components/button.js

```javascript
import styles from './submit-button.css';
buttonElem.outerHTML= `
  <button class=${styles.normal}>Submit</button>
`;
```

index.html

```html
<button class="components_button__normal__abc5436">
  Submit
</button>
```

### Composes

components/button.css

```css
.common { /* font-size, border-radius */ }
.normal { composes: common; /* blue color */ }
.error { composes: common; /* red color */ }
```

components/button.js

```javascript
import styles from './submit-button.css';

buttonElem.outerHTML= `
  <button class=${styles.normal}>Submit</button>
`;
```

index.html

```html
<button class="components_button__common__abc5436
		       components_button__normal__def6547">
  Submit
</button>
```

### Share between files

shared/colors.css

```css
.primary {
  color: #720;
}
.secondary {
  color: #777;
}
```

components/button.css

```css
.common { /* ... */ }
.normal {
  composes: common;
  composes: primary from "../shared/colors.css";
}
```

### [Flexbox](https://www.w3.org/TR/css-flexbox-1/)

- [Example](http://codepen.io/christianv/pen/yOzRjE)
- [Support](http://caniuse.com/#feat=flexbox)
- [CSS-Tricks: A complete guide to flexbox](https://css-tricks.com/snippets/css/a-guide-to-flexbox/)

```scss
.flex-title {
  display: flex;
  align-items: flex-end;
  flex-wrap: wrap;
  .title-main {
    flex-grow: 1;
  }
}
```

### [Multi Column](https://www.w3.org/TR/css3-multicol/)

- [Example](http://caniuse.com/#feat=flexbox)
- [Support](http://caniuse.com/#feat=multicolumn)

```css
.main {
  column-count: 3;
  column-gap: 30px;
  column-rule: 1px dotted #999999;
}
```

### [Grid](https://www.w3.org/TR/css3-grid-layout/)

- [Example](http://codepen.io/christianv/pen/NNaOoy)
- [Support](http://caniuse.com/#feat=css-grid)
- [CSS-Tricks: A complete guide to gird](https://css-tricks.com/snippets/css/complete-guide-grid/)

```css
.sidebar { grid-area: sidebar; }
.content { grid-area: content; }
.wrapper {
  display: grid;
  grid-gap: 1em;
  grid-template-areas: "sidebar"
                       "content"
}
```

## New CSS feature

- Use them today - [cssnext](https://github.com/MoOx/postcss-cssnext)
- [Custom Properties](https://drafts.csswg.org/css-variables/)
- [Custom Media Queries](https://drafts.csswg.org/mediaqueries/)
- [Custom Selectors](https://drafts.csswg.org/selectors/)
- [Color Functions](https://drafts.csswg.org/css-color/)
- [4/8 Digit Hex Notation](https://drafts.csswg.org/css-color/#hex-notation)

[Autoprefixer](https://github.com/postcss/autoprefixer)

## References

- [ppt: css in 2016](http://christianvuerings.github.io/presentations/css-2016/)
